PBE/PBE/urls.py
from django.apps import apps
from django.urls import include, path
from django.contrib import admin
from catalogue_override import urls as catalogue_urls 
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
     path('i18n/', include('django.conf.urls.i18n')),

    # The Django admin is not officially supported; expect breakage.
    # Nonetheless, it's often useful for debugging.

    path('admin/', admin.site.urls),
    path('api/', include('users.urls')),
    path('api/', include('produtos.urls')),
    path('carrinho/', include('carrinho.urls', namespace='carrinho')),
    #path('fornecedor/', include('fornecedores.urls')),
    path('dashboard/fornecedores/', include('fornecedores.urls', namespace='fornecedores')),
    #path('dashboard/', RedirectView.as_view(url='/dashboard/fornecedor/', permanent=False)),
    path('catalogue/', include(catalogue_urls)),
    path('', include(apps.get_app_config('oscar').urls[0])),  # Include the main application URLs
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PBE/fornecedores/urls.py
# fornecedores/urls.py
from django.urls import path
from .views import (
    FornecedorDashboardView,
    ProdutoFormTemplate,
    ProdutoListView,
    ProdutoCreateView,
    ProdutoUpdateView,
    ProdutoDeleteView,
    EncomendaListView,
    EstatisticasView,
    SupplierOrderListView,
)

app_name = 'fornecedores'

urlpatterns = [
    path('', FornecedorDashboardView.as_view(), name='dashboard'),
    path('produtos/', ProdutoListView.as_view(), name='produto-list'),
    #path('produtos/novo/', ProdutoCreateView.as_view(), name='produto-create'),
    path('produtos/adicionar/', ProdutoFormTemplate.as_view(), name='produto-add'),
    path('produtos/<int:pk>/editar/', ProdutoUpdateView.as_view(), name='produto-update'),
    path('produtos/<int:pk>/remover/', ProdutoDeleteView.as_view(), name='produto-delete'),
    path('encomendas/', EncomendaListView.as_view(), name='encomenda-list'),
    path('estatisticas/', EstatisticasView.as_view(), name='estatisticas'),
    path('dashboard/', FornecedorDashboardView.as_view(), name='dashboard'),
    path('orders/', SupplierOrderListView.as_view(), name='orders'),
]

PBE/produtos/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from produtos.views import ListaCategoriasView, ProdutoViewSet


router = DefaultRouter()
router.register(r'produtos', ProdutoViewSet, basename='produtos')
#router.register(r'categorias', CategoriaViewSet, basename='categoria')

urlpatterns = [
    path('', include(router.urls)),
    path('categorias/', ListaCategoriasView.as_view(), name='categorias-lista'),
]

PBE/fornecedores/models.py
# fornecedores/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.conf import settings

User = get_user_model()

class Fornecedor(models.Model):
    usuario = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='fornecedor'
    )
    nome_empresa = models.CharField(max_length=255)
    cnpj = models.CharField(max_length=18, unique=True)
    #nif = models.CharField(max_length=18, unique=True)
    telefone = models.CharField(max_length=20)
    endereco = models.TextField()
    
    def __str__(self):
        return self.nome_empresa
    
class Encomenda(models.Model):
    STATUS_CHOICES = [
        ('pendente', 'Pendente'),
        ('processando', 'Processando'),
        ('enviado', 'Enviado'),
        ('entregue', 'Entregue'),
        ('cancelado', 'Cancelado'),
    ]
    
    numero = models.CharField(max_length=20, unique=True)
    cliente = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='encomendas')
    fornecedor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='encomendas_fornecedor')
    data_criacao = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pendente')
    
    class Meta:
        ordering = ['-data_criacao']
    
    def __str__(self):
        return f"Encomenda #{self.numero}"
    
    @property
    def status_cor(self):
        cores = {
            'pendente': 'warning',
            'processando': 'info',
            'enviado': 'primary',
            'entregue': 'success',
            'cancelado': 'danger',
        }
        return cores.get(self.status, 'secondary')

PBE/dashboard/catalogue/views.py
# pylint: disable=attribute-defined-outside-init
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django_tables2 import SingleTableMixin, SingleTableView

from oscar.core.loading import get_class, get_classes, get_model
from oscar.views.generic import ObjectLookupView

(
    ProductForm,
    ProductClassSelectForm,
    ProductSearchForm,
    ProductClassForm,
    CategoryForm,
    StockAlertSearchForm,
    AttributeOptionGroupForm,
    OptionForm,
) = get_classes(
    "dashboard.catalogue.forms",
    (
        "ProductForm",
        "ProductClassSelectForm",
        "ProductSearchForm",
        "ProductClassForm",
        "CategoryForm",
        "StockAlertSearchForm",
        "AttributeOptionGroupForm",
        "OptionForm",
    ),
)
(
    StockRecordFormSet,
    ProductCategoryFormSet,
    ProductImageFormSet,
    ProductRecommendationFormSet,
    ProductAttributesFormSet,
    AttributeOptionFormSet,
) = get_classes(
    "dashboard.catalogue.formsets",
    (
        "StockRecordFormSet",
        "ProductCategoryFormSet",
        "ProductImageFormSet",
        "ProductRecommendationFormSet",
        "ProductAttributesFormSet",
        "AttributeOptionFormSet",
    ),
)
ProductTable, CategoryTable, AttributeOptionGroupTable, OptionTable = get_classes(
    "dashboard.catalogue.tables",
    ("ProductTable", "CategoryTable", "AttributeOptionGroupTable", "OptionTable"),
)
(PopUpWindowCreateMixin, PopUpWindowUpdateMixin, PopUpWindowDeleteMixin) = get_classes(
    "dashboard.views",
    ("PopUpWindowCreateMixin", "PopUpWindowUpdateMixin", "PopUpWindowDeleteMixin"),
)
PartnerProductFilterMixin = get_class(
    "dashboard.catalogue.mixins", "PartnerProductFilterMixin"
)
Product = get_model("catalogue", "Product")
Category = get_model("catalogue", "Category")
ProductImage = get_model("catalogue", "ProductImage")
ProductCategory = get_model("catalogue", "ProductCategory")
ProductClass = get_model("catalogue", "ProductClass")
StockRecord = get_model("partner", "StockRecord")
StockAlert = get_model("partner", "StockAlert")
Partner = get_model("partner", "Partner")
AttributeOptionGroup = get_model("catalogue", "AttributeOptionGroup")
Option = get_model("catalogue", "Option")


class ProductListView(PartnerProductFilterMixin, SingleTableView):
    """
    Dashboard view of the product list.
    Supports the permission-based dashboard.
    """

    template_name = "oscar/dashboard/catalogue/product_list.html"
    form_class = ProductSearchForm
    productclass_form_class = ProductClassSelectForm
    table_class = ProductTable
    context_table_name = "products"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["form"] = self.form
        ctx["productclass_form"] = self.productclass_form_class()
        ctx["has_products"] = self.get_queryset().exists()
        return ctx

    def get_description(self, form):
        if form.is_valid() and any(form.cleaned_data.values()):
            return _("Product search results")
        return _("Products")

    def get_table(self, **kwargs):
        if "recently_edited" in self.request.GET:
            kwargs.update(dict(orderable=False))

        table = super().get_table(**kwargs)
        table.caption = self.get_description(self.form)
        return table

    def get_table_pagination(self, table):
        return dict(per_page=settings.OSCAR_DASHBOARD_ITEMS_PER_PAGE)

    def get_queryset(self):
        """
        Build the queryset for this list
        """
        queryset = Product.objects.browsable_dashboard().base_queryset()
        queryset = self.filter_queryset(queryset)
        queryset = self.apply_search(queryset)
        return queryset

    def apply_search(self, queryset):
        """
        Search through the filtered queryset.

        We must make sure that we don't return search results that the user is not allowed
        to see (see filter_queryset).
        """
        self.form = self.form_class(self.request.GET)

        if not self.form.is_valid():
            return queryset

        data = self.form.cleaned_data

        upc = data.get("upc")
        if upc:
            # Filter the queryset by upc
            # For usability reasons, we first look at exact matches and only return
            # them if there are any. Otherwise we return all results
            # that contain the UPC.

            # Look up all matches (child products, products not allowed to access) ...
            matches_upc = Product.objects.filter(
                Q(upc__iexact=upc) | Q(children__upc__iexact=upc)
            )

            # ... and use that to pick all standalone or parent products that the user is
            # allowed to access.
            qs_match = queryset.filter(
                Q(id__in=matches_upc.values("id"))
                | Q(id__in=matches_upc.values("parent_id"))
            )

            if qs_match.exists():
                # If there's a direct UPC match, return just that.
                queryset = qs_match
            else:
                # No direct UPC match. Let's try the same with an icontains search.
                matches_upc = Product.objects.filter(
                    Q(upc__icontains=upc) | Q(children__upc__icontains=upc)
                )
                queryset = queryset.filter(
                    Q(id__in=matches_upc.values("id"))
                    | Q(id__in=matches_upc.values("parent_id"))
                )

        title = data.get("title")
        if title:
            queryset = queryset.filter(
                Q(title__icontains=title) | Q(children__title__icontains=title)
            )

        return queryset.distinct()


class ProductCreateRedirectView(generic.RedirectView):
    permanent = False
    productclass_form_class = ProductClassSelectForm

    def get_product_create_url(self, product_class):
        """Allow site to provide custom URL"""
        return reverse(
            "dashboard:catalogue-product-create",
            kwargs={"product_class_slug": product_class.slug},
        )

    def get_invalid_product_class_url(self):
        messages.error(self.request, _("Please choose a product type"))
        return reverse("dashboard:catalogue-product-list")

    def get_redirect_url(self, *args, **kwargs):
        form = self.productclass_form_class(self.request.GET)
        if form.is_valid():
            product_class = form.cleaned_data["product_class"]
            return self.get_product_create_url(product_class)

        else:
            return self.get_invalid_product_class_url()


class ProductCreateUpdateView(PartnerProductFilterMixin, generic.UpdateView):
    """
    Dashboard view that is can both create and update products of all kinds.
    It can be used in three different ways, each of them with a unique URL
    pattern:
    - When creating a new standalone product, this view is called with the
      desired product class
    - When editing an existing product, this view is called with the product's
      primary key. If the product is a child product, the template considerably
      reduces the available form fields.
    - When creating a new child product, this view is called with the parent's
      primary key.

    Supports the permission-based dashboard.
    """

    template_name = "oscar/dashboard/catalogue/product_update.html"
    model = Product
    context_object_name = "product"

    form_class = ProductForm
    category_formset = ProductCategoryFormSet
    image_formset = ProductImageFormSet
    recommendations_formset = ProductRecommendationFormSet
    stockrecord_formset = StockRecordFormSet

    creating = False
    parent = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.formsets = {
            "category_formset": self.category_formset,
            "image_formset": self.image_formset,
            "recommended_formset": self.recommendations_formset,
            "stockrecord_formset": self.stockrecord_formset,
        }

    def dispatch(self, request, *args, **kwargs):
        resp = super().dispatch(request, *args, **kwargs)
        return self.check_objects_or_redirect() or resp

    def check_objects_or_redirect(self):
        """
        Allows checking the objects fetched by get_object and redirect
        if they don't satisfy our needs.
        Is used to redirect when create a new variant and the specified
        parent product can't actually be turned into a parent product.
        """
        if self.creating and self.parent is not None:
            is_valid, reason = self.parent.can_be_parent(give_reason=True)
            if not is_valid:
                messages.error(self.request, reason)
                return redirect("dashboard:catalogue-product-list")

    def get_queryset(self):
        """
        Filter products that the user doesn't have permission to update
        """
        return self.filter_queryset(Product.objects.all())

    def get_object(self, queryset=None):
        """
        This parts allows generic.UpdateView to handle creating products as
        well. The only distinction between an UpdateView and a CreateView
        is that self.object is None. We emulate this behavior.

        This method is also responsible for setting self.product_class and
        self.parent.
        """
        self.creating = "pk" not in self.kwargs
        if self.creating:
            # Specifying a parent product is only done when creating a child
            # product.
            parent_pk = self.kwargs.get("parent_pk")
            if parent_pk is None:
                self.parent = None

PBE/dashboard/communications/views.py
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.template import TemplateSyntaxError
from django.utils.translation import gettext_lazy as _
from django.views import generic

from oscar.core.loading import get_class, get_model

CommunicationEventType = get_model("communication", "CommunicationEventType")
CommunicationEventTypeForm = get_class(
    "dashboard.communications.forms", "CommunicationEventTypeForm"
)
Dispatcher = get_class("communication.utils", "Dispatcher")


class ListView(generic.ListView):
    model = CommunicationEventType
    template_name = "oscar/dashboard/comms/list.html"
    context_object_name = "commtypes"


class UpdateView(generic.UpdateView):
    model = CommunicationEventType
    form_class = CommunicationEventTypeForm
    template_name = "oscar/dashboard/comms/detail.html"
    context_object_name = "commtype"
    success_url = "."
    slug_field = "code"

    def form_invalid(self, form):
        messages.error(
            self.request,
            _(
                "The submitted form was not valid, please correct "
                "the errors and resubmit"
            ),
        )
        return super().form_invalid(form)

    def form_valid(self, form):
        if "send_preview" in self.request.POST:
            return self.send_preview(form)
        if "show_preview" in self.request.POST:
            return self.show_preview(form)
        messages.success(self.request, _("Email saved"))
        return super().form_valid(form)

    def get_messages_context(self, form):
        ctx = {"user": self.request.user, "site": get_current_site(self.request)}
        ctx.update(form.get_preview_context())
        return ctx

    def show_preview(self, form):
        ctx = super().get_context_data()
        ctx["form"] = form

        commtype = form.save(commit=False)
        commtype_ctx = self.get_messages_context(form)
        try:
            msgs = commtype.get_messages(commtype_ctx)
        except TemplateSyntaxError as e:
            form.errors["__all__"] = form.error_class([str(e)])
            return self.render_to_response(ctx)

        ctx["show_preview"] = True
        ctx["preview"] = msgs
        return self.render_to_response(ctx)

    def send_preview(self, form):
        ctx = super().get_context_data()
        ctx["form"] = form

        commtype = form.save(commit=False)
        commtype_ctx = self.get_messages_context(form)
        try:
            msgs = commtype.get_messages(commtype_ctx)
        except TemplateSyntaxError as e:
            form.errors["__all__"] = form.error_class([str(e)])
            return self.render_to_response(ctx)

        email = form.cleaned_data["preview_email"]
        dispatch = Dispatcher()
        dispatch.send_email_messages(email, msgs)
        messages.success(self.request, _("A preview email has been sent to %s") % email)

        return self.render_to_response(ctx)

PBE/fornecedores/templates/fornecedores/base.html
{% extends "oscar/dashboard/layout.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <!-- Menu Lateral -->
        <div class="col-md-3 col-lg-2 d-md-block sidebar dashboard-nav">
            <div class="sidebar-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link {% if 'fornecedores/dashboard' in request.path %}active{% endif %}" 
                           href="{% url 'fornecedores:dashboard' %}">
                            <i class="fas fa-tachometer-alt"></i> Dashboard
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if 'fornecedores/produtos' in request.path %}active{% endif %}" 
                           href="{% url 'fornecedores:produto-list' %}">
                            <i class="fas fa-box-open"></i> Meus Produtos
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% if 'fornecedores/encomendas' in request.path %}active{% endif %}" 
                           href="{% url 'fornecedores:encomenda-list' %}">
                            <i class="fas fa-clipboard-list"></i> Encomendas
                        </a>
                    </li>
                </ul>
            </div>
        </div>

        <!-- Conteúdo Principal -->
        <div class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            {% block dashboard_content %}
            {% endblock %}
        </div>
    </div>
</div>
{% endblock %}

PBE/fornecedores/templates/fornecedores/dashboard.html
{% extends "oscar/dashboard/fornecedores/base.html" %}

{% block dashboard_content %}
<div class="page-header">
    <h1>Dashboard do Fornecedor</h1>
</div>

<div class="row">
    <!-- Card de Produtos -->
    <div class="col-md-4">
        <div class="card border-primary mb-4">
            <div class="card-header bg-primary text-white">
                <i class="fas fa-boxes"></i> Meus Produtos
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ produtos_count }} Produtos</h5>
                <a href="{% url 'fornecedores:produto-list' %}" class="btn btn-primary">
                    Gerenciar Produtos
                </a>
            </div>
        </div>
    </div>

    <!-- Card de Encomendas -->
    <div class="col-md-4">
        <div class="card border-success mb-4">
            <div class="card-header bg-success text-white">
                <i class="fas fa-shopping-cart"></i> Encomendas
            </div>
            <div class="card-body">
                <h5 class="card-title">{{ encomendas_count }} Encomendas</h5>
                <a href="{% url 'fornecedores:encomenda-list' %}" class="btn btn-success">
                    Ver Encomendas
                </a>
            </div>
        </div>
    </div>

    <!-- Card de Estatísticas -->
    <div class="col-md-4">
        <div class="card border-info mb-4">
            <div class="card-header bg-info text-white">
                <i class="fas fa-chart-line"></i> Vendas
            </div>
            <div class="card-body">
                <h5 class="card-title">R$ {{ total_vendas|floatformat:2 }}</h5>
                <a href="#" class="btn btn-info">
                    Ver Estatísticas
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

PBE/fornecedores/templates/fornecedores/encomenda_list.html
{% extends 'fornecedores/base.html' %}

{% block dashboard_title %}Minhas Encomendas{% endblock %}

{% block dashboard_content %}
<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Número</th>
                <th>Data</th>
                <th>Cliente</th>
                <th>Total</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for encomenda in encomendas %}
            <tr>
                <td>{{ encomenda.numero }}</td>
                <td>{{ encomenda.data_criacao|date:"d/m/Y" }}</td>
                <td>{{ encomenda.cliente.get_full_name|default:encomenda.cliente.username }}</td>
                <td>R$ {{ encomenda.total|floatformat:2 }}</td>
                <td>
                    <span class="badge badge-{{ encomenda.status_cor }}">
                        {{ encomenda.get_status_display }}
                    </span>
                </td>
                <td>
                    <a href="{% url 'fornecedores:encomenda-detail' encomenda.id %}" 
                       class="btn btn-sm btn-outline-primary">
                        Detalhes
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">Nenhuma encomenda encontrada.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% if is_paginated %}
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">&laquo;</span>
        </li>
        {% endif %}
        
        {% for i in paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %}active{% endif %}">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
        {% endfor %}
        
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <span class="page-link">&raquo;</span>
        </li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

PBE/fornecedores/templates/fornecedores/orders.html
{% extends "oscar/base.html" %}
{% load i18n %}

{% block content %}
  <h2>{% trans "Minhas Encomendas" %}</h2>
  {% if orders %}
    <ul class="list-group">
      {% for order in orders %}
        <li class="list-group-item mb-3">
          <h5>
            {% trans "Encomenda" %} {{ order.number }}
            — {{ order.status|capfirst }}
            <small class="text-muted">({{ order.date_placed }})</small>
          </h5>
          <ul>
            {% for line in order.lines.all %}
              {% if line.product.fornecedor == request.user.fornecedorprofile %}
                <li>
                  {{ line.quantity }} × {{ line.product.title }}
                  — {{ line.line_price_excl_tax|currency }}
                </li>
              {% endif %}
            {% endfor %}
          </ul>
          <a href="{% url 'customer:order-detail' order.number %}" class="btn btn-sm btn-primary">
            {% trans "Ver detalhes" %}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p class="text-muted">{% trans "Ainda não há encomendas para você." %}</p>
  {% endif %}
{% endblock %}

PBE/fornecedores/templates/fornecedores/produto_confirm_delete.html
{% extends "oscar/dashboard/layout.html" %}

{% block content %}
<div class="container mt-4">
  <h2>Confirmar Remoção</h2>
  <p>Tens a certeza que deseja apagar o produto <strong>{{ object.nome }}</strong>?</p>
  <form method="post">
    {% csrf_token %}
    <a href="{% url 'fornecedores:produto-list' %}" class="btn btn-secondary">Cancelar</a>
    <button type="submit" class="btn btn-danger">Sim, apagar</button>
  </form>
</div>
{% endblock %}

PBE/fornecedores/templates/fornecedores/produto_edit.html
{% extends "oscar/dashboard/layout.html" %}

{% block title %}Editar Produto{% endblock %}

{% block breadcrumbs %}
<ul class="breadcrumb">
    <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
    <li><a href="{% url 'fornecedores:produto-list' %}">Produtos</a></li>
    <li class="active">Editar Produto</li>
</ul>
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h3>Editar Produto</h3>
    </div>
    <div class="card-body">
        <form method="post" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            {{ form.non_field_errors }}
            {% for field in form %}
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                    <label class="control-label col-sm-2">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field }}
                        {% for error in field.errors %}
                            <span class="help-block">{{ error }}</span>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                    <a href="{% url 'fornecedores:produto-list' %}" class="btn btn-default">Cancelar</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

PBE/fornecedores/templates/fornecedores/produto_form.html
{% extends 'fornecedores/base.html' %}

{% block dashboard_title %}
    {% if object %}Editar Produto{% else %}Adicionar Produto{% endif %}
{% endblock %}

{% block dashboard_content %}
<div class="container mt-5">
  <h2 class="mb-4">Adicionar Produto</h2>

<form id="produtoForm" enctype="multipart/form-data">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="nome">Nome</label>
        <input type="text" name="nome" class="form-control" required>
    </div>
    
    <div class="form-group">
        <label for="descricao">Descrição</label>
        <textarea name="descricao" class="form-control" required></textarea>
    </div>
    
    <div class="form-group">
        <label for="imagem">Imagem</label>
        <input type="file" name="imagem" class="form-control">
    </div>

    <div class="form-group">
        <label for="categoria">Categoria</label>
        <select name="categoria_id" class="form-control" required>
            {% for cat in categorias %}
                <option value="{{ cat.id }}">{{ cat.nome }}</option>
            {% endfor %}
        </select>
    </div>
    
    <div class="form-group">
        <label for="preco">Preço</label>
        <input type="number" step="0.01" name="preco" class="form-control" required>
    </div>

    <div class="form-group">
        <label for="unidade_venda">Unidade de Venda</label>
        <select name="unidade_venda" class="form-control" required>
            <option value="m2">Metro quadrado (m²)</option>
            <option value="m3">Metro cúbico (m³)</option>
            <option value="saco">Saco</option>
            <option value="kg">Quilograma (kg)</option>
            <option value="unid">Unidade</option>
        </select>
    </div>

    <div class="form-group">
        <label for="quantidade">Quantidade</label>
        <input type="number" name="quantidade" class="form-control" required>
    </div>

    <button type="submit" class="btn btn-primary">Salvar</button>
</form>
</div>
{% block extra_js %}

<script>
document.getElementById('produtoForm').addEventListener('submit', async function(event) {
    event.preventDefault();
    const form = new FormData(this);

    const response = await fetch('/api/produtos/', {
        method: 'POST',
        headers: {
            'X-CSRFToken': '{{ csrf_token }}',
        },
        body: form
    });

    if (response.ok) {
        alert("Produto adicionado com sucesso!");
        window.location.href = "{% url 'fornecedores:produto-list' %}";
    } else {
        const data = await response.json();
        alert("Erro ao adicionar produto: " + JSON.stringify(data));
    }
});
</script>
{% endblock %}
{% endblock %}s

PBE/fornecedores/templates/fornecedores/produto_list.html
{% extends 'fornecedores/base.html' %}

{% block dashboard_title %}Meus Produtos{% endblock %}



{% block dashboard_content %}

<div class="btn-group mr-2">
    <a href="{% url 'fornecedores:produto-add' %}" class="btn btn-sm btn-outline-secondary">
        <i class="fas fa-plus"></i> Adicionar Produto
    </a>
</div>

<div class="table-responsive">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Preço</th>
                <th>Estoque</th>
                <th>Status</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for produto in produtos %}
            <tr>
                <td>{{ produto.nome }}</td>
                <td>{{ produto.categoria }}</td>
                <td>€ {{ produto.preco|floatformat:2 }}</td>
                <td>{{ produto.quantidade  }} {{ produto.unidade_medida }}</td>
                <td>
                    {% if produto.quantidade > 0 %}
                    <span class="badge badge-success">Disponível</span>
                    {% else %}
                    <span class="badge badge-danger">Esgotado</span>
                    {% endif %}
                </td>
                <td>
                    <a href="{% url 'fornecedores:produto-update' produto.id %}" 
                       class="btn btn-sm btn-outline-primary">
                        <i class="fas fa-edit"></i>
                    </a>
                    <a href="{% url 'fornecedores:produto-delete' produto.id %}" 
                       class="btn btn-sm btn-outline-danger">
                        <i class="fas fa-trash"></i>
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">Nenhum produto cadastrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}