PBE/PBE/urls.py
from django.apps import apps
from django.urls import include, path
from django.contrib import admin
from catalogue_override import urls as catalogue_urls 
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
     path('i18n/', include('django.conf.urls.i18n')),

    # The Django admin is not officially supported; expect breakage.
    # Nonetheless, it's often useful for debugging.

    path('admin/', admin.site.urls),
    path('api/', include('users.urls')),
    path('api/', include('produtos.urls')),
    path('carrinho/', include('carrinho.urls', namespace='carrinho')),
    #path('fornecedor/', include('fornecedores.urls')),
    path('dashboard/fornecedores/', include('fornecedores.urls', namespace='fornecedores')),
    #path('dashboard/', RedirectView.as_view(url='/dashboard/fornecedor/', permanent=False)),
    path('catalogue/', include(catalogue_urls)),
    path('', include(apps.get_app_config('oscar').urls[0])),  # Include the main application URLs
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PBE/carrinho/urls.py
from django.urls import path
from .views import (
    adicionar_ao_carrinho,
    remover_do_carrinho,
    ver_carrinho,
    finalizar_compra,
)

app_name = 'carrinho'

urlpatterns = [
    path('', ver_carrinho, name='ver-carrinho'),
    path('adicionar/<int:produto_id>/', adicionar_ao_carrinho, name='adicionar'),
    path('remover/<int:produto_id>/', remover_do_carrinho, name='remover'),
    path('finalizar/', finalizar_compra, name='finalizar-compra'),
]

PBE/catalogue_override/urls.py
from django.urls import path
from produtos.models import Produto, Categoria
from .views import CustomCatalogueView

app_name = 'catalogue_override'

urlpatterns = [
    path('', CustomCatalogueView.as_view(), name='product-list'),
    path('', CustomCatalogueView.as_view(), name='browse'),
]

PBE/catalogue_override/views.py
from django.shortcuts import render
from django.views.generic import ListView
from produtos.models import Produto, Categoria
from django.views.generic import TemplateView
# Create your views here.

#class CustomCatalogueView(ListView):
    #model = Produto
    #template_name = 'oscar/catalogue/browse.html'
    #context_object_name = 'products'
    # paginate_by = 12  # Número de produtos por página

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     category_slug = self.request.GET.get('category')  # Obtém o slug da categoria da query string

    #     if category_slug:
    #         queryset = queryset.filter(categoria__slug=category_slug)  # Filtra produtos pela categoria
        
    #     return queryset.order_by('nome')  # Ordena os produtos pelo nome

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['categories'] = Categoria.objects.all()  # Adiciona todas as categorias ao contexto
    #     context['current_category'] = self.request.GET.get('category')  # Adiciona a categoria atual ao contexto
    #    return context
    
class CustomCatalogueView(TemplateView):
    template_name = 'oscar/catalogue/browse.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categoria_id = self.request.GET.get('category')

        if categoria_id:
            produtos = Produto.objects.filter(categoria_id=categoria_id)
        else:
            produtos = Produto.objects.all()

        context['products'] = produtos
        context['categories'] = Categoria.objects.all()
        return context

PBE/dashboard/catalogue/views.py
# pylint: disable=attribute-defined-outside-init
from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import generic
from django_tables2 import SingleTableMixin, SingleTableView

from oscar.core.loading import get_class, get_classes, get_model
from oscar.views.generic import ObjectLookupView

(
    ProductForm,
    ProductClassSelectForm,
    ProductSearchForm,
    ProductClassForm,
    CategoryForm,
    StockAlertSearchForm,
    AttributeOptionGroupForm,
    OptionForm,
) = get_classes(
    "dashboard.catalogue.forms",
    (
        "ProductForm",
        "ProductClassSelectForm",
        "ProductSearchForm",
        "ProductClassForm",
        "CategoryForm",
        "StockAlertSearchForm",
        "AttributeOptionGroupForm",
        "OptionForm",
    ),
)
(
    StockRecordFormSet,
    ProductCategoryFormSet,
    ProductImageFormSet,
    ProductRecommendationFormSet,
    ProductAttributesFormSet,
    AttributeOptionFormSet,
) = get_classes(
    "dashboard.catalogue.formsets",
    (
        "StockRecordFormSet",
        "ProductCategoryFormSet",
        "ProductImageFormSet",
        "ProductRecommendationFormSet",
        "ProductAttributesFormSet",
        "AttributeOptionFormSet",
    ),
)
ProductTable, CategoryTable, AttributeOptionGroupTable, OptionTable = get_classes(
    "dashboard.catalogue.tables",
    ("ProductTable", "CategoryTable", "AttributeOptionGroupTable", "OptionTable"),
)
(PopUpWindowCreateMixin, PopUpWindowUpdateMixin, PopUpWindowDeleteMixin) = get_classes(
    "dashboard.views",
    ("PopUpWindowCreateMixin", "PopUpWindowUpdateMixin", "PopUpWindowDeleteMixin"),
)
PartnerProductFilterMixin = get_class(
    "dashboard.catalogue.mixins", "PartnerProductFilterMixin"
)
Product = get_model("catalogue", "Product")
Category = get_model("catalogue", "Category")
ProductImage = get_model("catalogue", "ProductImage")
ProductCategory = get_model("catalogue", "ProductCategory")
ProductClass = get_model("catalogue", "ProductClass")
StockRecord = get_model("partner", "StockRecord")
StockAlert = get_model("partner", "StockAlert")
Partner = get_model("partner", "Partner")
AttributeOptionGroup = get_model("catalogue", "AttributeOptionGroup")
Option = get_model("catalogue", "Option")


class ProductListView(PartnerProductFilterMixin, SingleTableView):
    """
    Dashboard view of the product list.
    Supports the permission-based dashboard.
    """

    template_name = "oscar/dashboard/catalogue/product_list.html"
    form_class = ProductSearchForm
    productclass_form_class = ProductClassSelectForm
    table_class = ProductTable
    context_table_name = "products"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["form"] = self.form
        ctx["productclass_form"] = self.productclass_form_class()
        ctx["has_products"] = self.get_queryset().exists()
        return ctx

    def get_description(self, form):
        if form.is_valid() and any(form.cleaned_data.values()):
            return _("Product search results")
        return _("Products")

    def get_table(self, **kwargs):
        if "recently_edited" in self.request.GET:
            kwargs.update(dict(orderable=False))

        table = super().get_table(**kwargs)
        table.caption = self.get_description(self.form)
        return table

    def get_table_pagination(self, table):
        return dict(per_page=settings.OSCAR_DASHBOARD_ITEMS_PER_PAGE)

    def get_queryset(self):
        """
        Build the queryset for this list
        """
        queryset = Product.objects.browsable_dashboard().base_queryset()
        queryset = self.filter_queryset(queryset)
        queryset = self.apply_search(queryset)
        return queryset

    def apply_search(self, queryset):
        """
        Search through the filtered queryset.

        We must make sure that we don't return search results that the user is not allowed
        to see (see filter_queryset).
        """
        self.form = self.form_class(self.request.GET)

        if not self.form.is_valid():
            return queryset

        data = self.form.cleaned_data

        upc = data.get("upc")
        if upc:
            # Filter the queryset by upc
            # For usability reasons, we first look at exact matches and only return
            # them if there are any. Otherwise we return all results
            # that contain the UPC.

            # Look up all matches (child products, products not allowed to access) ...
            matches_upc = Product.objects.filter(
                Q(upc__iexact=upc) | Q(children__upc__iexact=upc)
            )

            # ... and use that to pick all standalone or parent products that the user is
            # allowed to access.
            qs_match = queryset.filter(
                Q(id__in=matches_upc.values("id"))
                | Q(id__in=matches_upc.values("parent_id"))
            )

            if qs_match.exists():
                # If there's a direct UPC match, return just that.
                queryset = qs_match
            else:
                # No direct UPC match. Let's try the same with an icontains search.
                matches_upc = Product.objects.filter(
                    Q(upc__icontains=upc) | Q(children__upc__icontains=upc)
                )
                queryset = queryset.filter(
                    Q(id__in=matches_upc.values("id"))
                    | Q(id__in=matches_upc.values("parent_id"))
                )

        title = data.get("title")
        if title:
            queryset = queryset.filter(
                Q(title__icontains=title) | Q(children__title__icontains=title)
            )

        return queryset.distinct()


class ProductCreateRedirectView(generic.RedirectView):
    permanent = False
    productclass_form_class = ProductClassSelectForm

    def get_product_create_url(self, product_class):
        """Allow site to provide custom URL"""
        return reverse(
            "dashboard:catalogue-product-create",
            kwargs={"product_class_slug": product_class.slug},
        )

    def get_invalid_product_class_url(self):
        messages.error(self.request, _("Please choose a product type"))
        return reverse("dashboard:catalogue-product-list")

    def get_redirect_url(self, *args, **kwargs):
        form = self.productclass_form_class(self.request.GET)
        if form.is_valid():
            product_class = form.cleaned_data["product_class"]
            return self.get_product_create_url(product_class)

        else:
            return self.get_invalid_product_class_url()


class ProductCreateUpdateView(PartnerProductFilterMixin, generic.UpdateView):
    """
    Dashboard view that is can both create and update products of all kinds.
    It can be used in three different ways, each of them with a unique URL
    pattern:
    - When creating a new standalone product, this view is called with the
      desired product class
    - When editing an existing product, this view is called with the product's
      primary key. If the product is a child product, the template considerably
      reduces the available form fields.
    - When creating a new child product, this view is called with the parent's
      primary key.

    Supports the permission-based dashboard.
    """

    template_name = "oscar/dashboard/catalogue/product_update.html"
    model = Product
    context_object_name = "product"

    form_class = ProductForm
    category_formset = ProductCategoryFormSet
    image_formset = ProductImageFormSet
    recommendations_formset = ProductRecommendationFormSet
    stockrecord_formset = StockRecordFormSet

    creating = False
    parent = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.formsets = {
            "category_formset": self.category_formset,
            "image_formset": self.image_formset,
            "recommended_formset": self.recommendations_formset,
            "stockrecord_formset": self.stockrecord_formset,
        }

    def dispatch(self, request, *args, **kwargs):
        resp = super().dispatch(request, *args, **kwargs)
        return self.check_objects_or_redirect() or resp

    def check_objects_or_redirect(self):
        """
        Allows checking the objects fetched by get_object and redirect
        if they don't satisfy our needs.
        Is used to redirect when create a new variant and the specified
        parent product can't actually be turned into a parent product.
        """
        if self.creating and self.parent is not None:
            is_valid, reason = self.parent.can_be_parent(give_reason=True)
            if not is_valid:
                messages.error(self.request, reason)
                return redirect("dashboard:catalogue-product-list")

    def get_queryset(self):
        """
        Filter products that the user doesn't have permission to update
        """
        return self.filter_queryset(Product.objects.all())

    def get_object(self, queryset=None):
        """
        This parts allows generic.UpdateView to handle creating products as
        well. The only distinction between an UpdateView and a CreateView
        is that self.object is None. We emulate this behavior.

        This method is also responsible for setting self.product_class and
        self.parent.
        """
        self.creating = "pk" not in self.kwargs
        if self.creating:
            # Specifying a parent product is only done when creating a child
            # product.
            parent_pk = self.kwargs.get("parent_pk")
            if parent_pk is None:
                self.parent = None

PBE/catalogue_override/templates/oscar/catalogue/browse.html
{# <p style="color:red"> Estou no template override!</p> Mensagem de teste para indicar que o template override está funcionando #}
{% extends "oscar/layout_2_col.html" %}

{% load basket_tags %}
{% load category_tags %}
{% load product_tags %}
{% load i18n %}

{% block title %}
    {% if summary %}{{ summary }} |{% endif %} {{ block.super }}
{% endblock %}

{% block headertext %}{{ summary }}{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ homepage_url }}">{% trans "Home" %}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ summary }}</li>
        </ol>
    </nav>
{% endblock breadcrumbs %}

{% block column_left %}
    {% category_tree as tree_categories %}
    {% if tree_categories %}
        <h4>{% trans "Show results for" %}</h4>
        <div class="side_categories card card-body bg-light">
            <ul class="nav nav-list flex-column">
                {% for tree_category in tree_categories %}
                    <li class="mt-2">
                        <a href="{{ tree_category.url }}">
                            {% if tree_category.pk == category.pk %}
                                <strong>{{ tree_category.name }}</strong>
                            {% else %}
                                {{ tree_category.name }}
                            {% endif %}
                        </a>

                        {% if tree_category.has_children %}<ul>{% else %}</li>{% endif %}
                        {% for n in tree_category.num_to_close %}
                            </ul></li>
                        {% endfor %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    {% if has_facets %}
        <h4>{% trans "Refine by" %}</h4>
        <div class="side_categories card card-body bg-light">
            {% for field, data in facet_data.items %}
                {% if data.results %}
                    {% include 'oscar/search/partials/facet.html' with name=data.name items=data.results %}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-3">
        <h4>Categorias</h4>
        <ul class="list-group">
            {% for categoria in categories %}
                <li class="list-group-item">
                    <a href="{% url 'catalogue_override:browse' %}?category={{ categoria.id }}">
                        {{ categoria.nome }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-sm-9">
        <h2>Produtos</h2>
        <div class="row">
            {% for produto in products %}
                <div class="col-md-4">
                    <div class="card mb-3">
                        <img src="{{ produto.imagem.url }}" class="card-img-top" alt="{{ produto.nome }}" style="width: 100%; height: 200px; object-fit: cover;">
                        <div class="card-body">
                            <h5 class="card-title">{{ produto.nome }}</h5>
                            <p>{{ produto.descricao|truncatewords:15 }}</p>
                            <p>Preço: €{{ produto.preco }}</p>
                            <p>
                                {% if produto.quantidade > 0 %}
                                    <span class="text-success">Disponível</span>
                                {% else %}
                                    <span class="text-danger">Esgotado</span>
                                {% endif %}
                            </p>
                            {% if request.user.is_authenticated %}
                                <form method="post" action="{% url 'carrinho:adicionar' produto.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="product_id" value="{{ produto.id }}">
                                    <input type="hidden" name="quantity" value="1">
                                    <button type="submit" class="btn btn-primary btn-sm">Adicionar ao carrinho</button>
                                </form>
                            {% else %}
                                <p><a href="/accounts/login/">Faça login para comprar</a></p>
                            {% endif %}

                        </div>
                    </div>
                </div>
            {% empty %}
                <p>Nenhum produto encontrado.</p>
            {% endfor %}
        </div>
    </div>
    
</div>
{% endblock %}

PBE/catalogue_override/templates/oscar/catalogue/product_list.html
{% extends "oscar/base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <h4>Categorias</h4>
            <ul class="nav flex-column">
                {% for categoria in categories %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{{ categoria.nome }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-9">
            <h2>Produtos</h2>
            <div class="row">
                {% for produto in products %}
                    <div class="col-md-4">
                        <div class="card mb-3">
                            <img src="{{ produto.imagem.url }}" class="card-img-top" alt="{{ produto.nome }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ produto.nome }}</h5>
                                <p class="card-text">{{ produto.descricao|truncatechars:100 }}</p>
                                <p><strong>Preço:</strong> € {{ produto.preco }}</p>
                                <p>
                                    <span class="badge {% if produto.quantidade > 0 %}badge-success{% else %}badge-danger{% endif %}">
                                        {% if produto.quantidade > 0 %} Disponível {% else %} Esgotado {% endif %}
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>
                {% empty %}
                    <p>Nenhum produto encontrado.</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}